/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.compomics.cell_coord.gui.load;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JEditorPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTree;

/**
 *
 * @author Paola
 */
public class LoadTracksPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoadTracksPanel
     */
    public LoadTracksPanel() {
        initComponents();
    }

    public JEditorPane getInfoEditorPane() {
        return infoEditorPane;
    }

    public JTextArea getChosenDirectoryTextArea() {
        return chosenDirectoryTextArea;
    }

    public JTree getDirectoryTree() {
        return directoryTree;
    }

    public JComboBox getFileFormatComboBox() {
        return fileFormatComboBox;
    }

    public JButton getImportFilesButton() {
        return importFilesButton;
    }

    public JButton getLoadDirectoryButton() {
        return loadDirectoryButton;
    }

    public JTable getTracksTable() {
        return tracksTable;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fileFormatComboBox = new javax.swing.JComboBox();
        loadDirectoryButton = new javax.swing.JButton();
        importFilesButton = new javax.swing.JButton();
        chosenDirectoryScrollPane = new javax.swing.JScrollPane();
        chosenDirectoryTextArea = new javax.swing.JTextArea();
        directoryScrollPane = new javax.swing.JScrollPane();
        directoryTree = new javax.swing.JTree();
        tracksScrollPane = new javax.swing.JScrollPane();
        tracksTable = new javax.swing.JTable();
        infoScrollPane = new javax.swing.JScrollPane();
        infoEditorPane = new javax.swing.JEditorPane();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Choose a file format");

        loadDirectoryButton.setText("Choose & Load Directory");

        importFilesButton.setText("Import Selected Files");

        chosenDirectoryScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Directory Loaded"));

        chosenDirectoryTextArea.setEditable(false);
        chosenDirectoryTextArea.setColumns(20);
        chosenDirectoryTextArea.setLineWrap(true);
        chosenDirectoryTextArea.setRows(5);
        chosenDirectoryTextArea.setBorder(null);
        chosenDirectoryTextArea.setCaretColor(new java.awt.Color(255, 255, 255));
        chosenDirectoryTextArea.setEnabled(false);
        chosenDirectoryScrollPane.setViewportView(chosenDirectoryTextArea);

        directoryScrollPane.setBorder(null);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Root (data)");
        directoryTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        directoryScrollPane.setViewportView(directoryTree);

        tracksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tracksScrollPane.setViewportView(tracksTable);

        infoScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Info"));

        infoEditorPane.setEditable(false);
        infoEditorPane.setContentType("text/html"); // NOI18N
        infoEditorPane.setText("<html>\n         1. Select the fomat of the files you want to import (<b>CSV</b>: comma separated values; <b>TSV</b>: tab separated values or <b>XLS/XLSX</b>: Microsoft Excel; <b>TrackMate</b>)\n         </br>\n         <br>\n\t\t <br>\n\t\t </br>\n         2. Choose the directory containing the cell tracking files to import.\n         </br>\n         <br>\n         </br>\n         <br>\n         3. Once the files are rendered in the data tree, select the ones you wish to import: if the import is successful, the tracks will appear in the data table underneath.\n      </p>\n   </body>\n</html>");
        infoScrollPane.setViewportView(infoEditorPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tracksScrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fileFormatComboBox, 0, 184, Short.MAX_VALUE)
                            .addComponent(loadDirectoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(importFilesButton, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(chosenDirectoryScrollPane))
                        .addGap(8, 8, 8)
                        .addComponent(directoryScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(infoScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(directoryScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fileFormatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loadDirectoryButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(importFilesButton)
                        .addGap(18, 18, 18)
                        .addComponent(chosenDirectoryScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(infoScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(tracksScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane chosenDirectoryScrollPane;
    private javax.swing.JTextArea chosenDirectoryTextArea;
    private javax.swing.JScrollPane directoryScrollPane;
    private javax.swing.JTree directoryTree;
    private javax.swing.JComboBox fileFormatComboBox;
    private javax.swing.JButton importFilesButton;
    private javax.swing.JEditorPane infoEditorPane;
    private javax.swing.JScrollPane infoScrollPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loadDirectoryButton;
    private javax.swing.JScrollPane tracksScrollPane;
    private javax.swing.JTable tracksTable;
    // End of variables declaration//GEN-END:variables
}
