/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.compomics.cell_coord.gui.load;

import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTree;

/**
 *
 * @author Paola
 */
public class LoadTrackMateFilesPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoadTrackMateFilesPanel
     */
    public LoadTrackMateFilesPanel() {
        initComponents();
    }

    public JTextArea getDirectoryTextArea() {
        return directoryTextArea;
    }

    public JTree getDirectoryTree() {
        return directoryTree;
    }

    public JButton getImportFilesButton() {
        return importFilesButton;
    }

    public JButton getLoadDirectoryButton() {
        return loadDirectoryButton;
    }

    public JTable getTracksTable() {
        return tracksTable;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadDirectoryButton = new javax.swing.JButton();
        importFilesButton = new javax.swing.JButton();
        currentDirectoryScrollPane = new javax.swing.JScrollPane();
        directoryTextArea = new javax.swing.JTextArea();
        directoryScrollPane = new javax.swing.JScrollPane();
        directoryTree = new javax.swing.JTree();
        jScrollPane1 = new javax.swing.JScrollPane();
        tracksTable = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(20, 20));

        loadDirectoryButton.setText("Choose & Load Directory");

        importFilesButton.setText("Import Selected Files");

        currentDirectoryScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Directory Loaded"));

        directoryTextArea.setEditable(false);
        directoryTextArea.setColumns(20);
        directoryTextArea.setLineWrap(true);
        directoryTextArea.setRows(5);
        directoryTextArea.setBorder(null);
        directoryTextArea.setCaretColor(new java.awt.Color(255, 255, 255));
        directoryTextArea.setEnabled(false);
        currentDirectoryScrollPane.setViewportView(directoryTextArea);

        directoryScrollPane.setBorder(null);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Root (data)");
        directoryTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        directoryScrollPane.setViewportView(directoryTree);

        tracksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tracksTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loadDirectoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(importFilesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(currentDirectoryScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(directoryScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(directoryScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loadDirectoryButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(importFilesButton)
                        .addGap(18, 18, 18)
                        .addComponent(currentDirectoryScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(269, 269, 269)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane currentDirectoryScrollPane;
    private javax.swing.JScrollPane directoryScrollPane;
    private javax.swing.JTextArea directoryTextArea;
    private javax.swing.JTree directoryTree;
    private javax.swing.JButton importFilesButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadDirectoryButton;
    private javax.swing.JTable tracksTable;
    // End of variables declaration//GEN-END:variables
}
