/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.compomics.cell_coord.gui.summary;

import javax.swing.JList;
import javax.swing.JTable;

/**
 *
 * @author Paola
 */
public class SummaryDataPanel extends javax.swing.JPanel {

    /**
     * Creates new form SummaryDataPanel
     */
    public SummaryDataPanel() {
        initComponents();
    }

    public JTable getSamplesTable() {
        return samplesTable;
    }

    public JTable getTrackSpotsTable() {
        return trackSpotsTable;
    }

    public JTable getTracksTable() {
        return tracksTable;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        samplesScrollPane = new javax.swing.JScrollPane();
        samplesTable = new javax.swing.JTable();
        tracksScrollPane = new javax.swing.JScrollPane();
        tracksTable = new javax.swing.JTable();
        trackSpotsScrollPane = new javax.swing.JScrollPane();
        trackSpotsTable = new javax.swing.JTable();
        infoScrollPane = new javax.swing.JScrollPane();
        infoEditorPane = new javax.swing.JEditorPane();

        samplesScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Samples"));

        samplesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        samplesScrollPane.setViewportView(samplesTable);

        tracksScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Cell Tracks"));

        tracksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tracksScrollPane.setViewportView(tracksTable);

        trackSpotsScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Track Spots"));

        trackSpotsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        trackSpotsScrollPane.setViewportView(trackSpotsTable);

        infoScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Info"));

        infoEditorPane.setEditable(false);
        infoEditorPane.setText("Click on a sample to inspect its data in the table below.\n\nFor each sample, the table lists:\n\n1. the number of cell tracks\n2. min and max (x, y) coordinates");
        infoScrollPane.setViewportView(infoEditorPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(samplesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(tracksScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addComponent(infoScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(trackSpotsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(samplesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(tracksScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(infoScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(trackSpotsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane infoEditorPane;
    private javax.swing.JScrollPane infoScrollPane;
    private javax.swing.JScrollPane samplesScrollPane;
    private javax.swing.JTable samplesTable;
    private javax.swing.JScrollPane trackSpotsScrollPane;
    private javax.swing.JTable trackSpotsTable;
    private javax.swing.JScrollPane tracksScrollPane;
    private javax.swing.JTable tracksTable;
    // End of variables declaration//GEN-END:variables
}
