/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.compomics.cell_coord.gui.summary;

import javax.swing.JEditorPane;
import javax.swing.JList;
import javax.swing.JTable;

/**
 *
 * @author Paola
 */
public class SummaryDataPanel extends javax.swing.JPanel {

    /**
     * Creates new form SummaryDataPanel
     */
    public SummaryDataPanel() {
        initComponents();
    }

    public JTable getSamplesTable() {
        return samplesTable;
    }

    public JTable getTrackSpotsTable() {
        return trackSpotsTable;
    }

    public JTable getTracksTable() {
        return tracksTable;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        samplesScrollPane = new javax.swing.JScrollPane();
        samplesTable = new javax.swing.JTable();
        tracksScrollPane = new javax.swing.JScrollPane();
        tracksTable = new javax.swing.JTable();
        trackSpotsScrollPane = new javax.swing.JScrollPane();
        trackSpotsTable = new javax.swing.JTable();
        infoScrollPane = new javax.swing.JScrollPane();
        infoEditorPane = new javax.swing.JEditorPane();

        samplesScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("1. Samples"));

        samplesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        samplesScrollPane.setViewportView(samplesTable);

        tracksScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("2. Cell Tracks"));

        tracksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tracksScrollPane.setViewportView(tracksTable);

        trackSpotsScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("3. Track Spots"));

        trackSpotsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        trackSpotsScrollPane.setViewportView(trackSpotsTable);

        infoScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Info"));

        infoEditorPane.setEditable(false);
        infoEditorPane.setContentType("text/html"); // NOI18N
        infoEditorPane.setText("<html>\n         1. Click on a sample in the table number <b>1</b> to visualize the correspondent cell tracks in the table number <b>2</b>.\n         </br>\n         <br>\n\t\t <br>\n\t\t </br>\n         2. Click on a cell track in the table number <b>2</b> to visualize the correspondent track spots in the final table number <b>3</b>.\n         </br>\n         <br>\n         </br>\n         <br>\n\t\t For each <b>track</b>, table number <b>2</b> lists:\n\t\t <br>- min and max <i>x</i> and <i>y</i> coordinates</br>\n\t\t <br>- net displacements in the <i>x</i> and <i>y</i> directions</br>\n\t\t <br>\n\t\t </br>\n\t\t <br>\n\t\t </br>\n         3. For each <b>track_spot</b>, table number <b>3</b> lists:\n <br>- the x coordinate</br>\n <br>- the y coordinate</br>\n <br>- the time point</br>\n      </p>\n   </body>\n</html>");
        infoScrollPane.setViewportView(infoEditorPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(samplesScrollPane)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tracksScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(infoScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(trackSpotsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(samplesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tracksScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(infoScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(trackSpotsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane infoEditorPane;
    private javax.swing.JScrollPane infoScrollPane;
    private javax.swing.JScrollPane samplesScrollPane;
    private javax.swing.JTable samplesTable;
    private javax.swing.JScrollPane trackSpotsScrollPane;
    private javax.swing.JTable trackSpotsTable;
    private javax.swing.JScrollPane tracksScrollPane;
    private javax.swing.JTable tracksTable;
    // End of variables declaration//GEN-END:variables
}
