/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.compomics.cell_coord.gui.summary;

import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JRadioButton;

/**
 *
 * @author Paola
 */
public class VisualizeTracksPanel extends javax.swing.JPanel {

    /**
     * Creates new form VisualizeTracksPanel
     */
    public VisualizeTracksPanel() {
        initComponents();
    }

    public JRadioButton getDoNotScaleAxesRadioButton() {
        return doNotScaleAxesRadioButton;
    }

    public JComboBox getnColumnsComboBox() {
        return nColumnsComboBox;
    }

    public JRadioButton getRawCoordRadioButton() {
        return rawCoordRadioButton;
    }

    public JRadioButton getRosePlotRadioButton() {
        return rosePlotRadioButton;
    }

    public JRadioButton getScaleAxesRadioButton() {
        return scaleAxesRadioButton;
    }

    public JPanel getTracksGraphicsParentPanel() {
        return tracksGraphicsParentPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        graphicOptionsPanel = new javax.swing.JPanel();
        scaleAxesRadioButton = new javax.swing.JRadioButton();
        doNotScaleAxesRadioButton = new javax.swing.JRadioButton();
        rawCoordRadioButton = new javax.swing.JRadioButton();
        rosePlotRadioButton = new javax.swing.JRadioButton();
        nColumnsComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        tracksGraphicsParentPanel = new javax.swing.JPanel();

        setLayout(new java.awt.GridBagLayout());

        graphicOptionsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));
        graphicOptionsPanel.setMinimumSize(new java.awt.Dimension(20, 20));
        graphicOptionsPanel.setPreferredSize(new java.awt.Dimension(20, 20));

        scaleAxesRadioButton.setText("scale axes");

        doNotScaleAxesRadioButton.setText("do not scale axes");

        rawCoordRadioButton.setText("plot raw coordinates");

        rosePlotRadioButton.setText("Rose plot (coordinates shifted to origin)");

        nColumnsComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("nr columns");

        javax.swing.GroupLayout graphicOptionsPanelLayout = new javax.swing.GroupLayout(graphicOptionsPanel);
        graphicOptionsPanel.setLayout(graphicOptionsPanelLayout);
        graphicOptionsPanelLayout.setHorizontalGroup(
            graphicOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graphicOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(graphicOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scaleAxesRadioButton)
                    .addComponent(doNotScaleAxesRadioButton))
                .addGap(18, 18, 18)
                .addGroup(graphicOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rosePlotRadioButton)
                    .addComponent(rawCoordRadioButton))
                .addGap(43, 43, 43)
                .addGroup(graphicOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nColumnsComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        graphicOptionsPanelLayout.setVerticalGroup(
            graphicOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, graphicOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(graphicOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scaleAxesRadioButton)
                    .addComponent(rawCoordRadioButton)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(graphicOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doNotScaleAxesRadioButton)
                    .addComponent(rosePlotRadioButton)
                    .addComponent(nColumnsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.15;
        add(graphicOptionsPanel, gridBagConstraints);

        tracksGraphicsParentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Cell Tracks"));
        tracksGraphicsParentPanel.setMinimumSize(new java.awt.Dimension(20, 20));
        tracksGraphicsParentPanel.setPreferredSize(new java.awt.Dimension(20, 20));
        tracksGraphicsParentPanel.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.85;
        add(tracksGraphicsParentPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton doNotScaleAxesRadioButton;
    private javax.swing.JPanel graphicOptionsPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox nColumnsComboBox;
    private javax.swing.JRadioButton rawCoordRadioButton;
    private javax.swing.JRadioButton rosePlotRadioButton;
    private javax.swing.JRadioButton scaleAxesRadioButton;
    private javax.swing.JPanel tracksGraphicsParentPanel;
    // End of variables declaration//GEN-END:variables
}
