/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.compomics.cell_coord.gui;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 * The main frame of the CellCoord plugin.
 *
 * @author Paola
 */
public class CellCoordFrame extends javax.swing.JFrame {

    /**
     * Creates new form CellCoordFrame
     */
    public CellCoordFrame() {
        initComponents();
        // set background to white
        this.getContentPane().setBackground(new Color(255, 255, 255));
        UIManager.put("nimbusBase", Color.lightGray);      // Base color
        UIManager.put("nimbusBlueGrey", Color.lightGray);  // BlueGrey
        UIManager.put("control", Color.white);         // Control
        UIManager.put("OptionPane.background", Color.white); // Background for option pane
        UIManager.put("info", Color.white); // Background for tooltip texts (info class)
    }

    public JButton getCancelButton() {
        return cancelButton;
    }

    public JPanel getTopPanel() {
        return topPanel;
    }

    public JPanel getLoadTracksParentPanel() {
        return loadTracksParentPanel;
    }

    public JPanel getSummaryDataParentPanel() {
        return summaryDataParentPanel;
    }

    public JPanel getVisualizeTracksParentPanel() {
        return visualizeTracksParentPanel;
    }

    public JPanel getComputationDataParentPanel() {
        return computationDataParentPanel;
    }

    public JPanel getComputationGraphParentPanel() {
        return computationGraphParentPanel;
    }

    public JButton getNextButton() {
        return nextButton;
    }

    public JButton getPreviousButton() {
        return previousButton;
    }

    public JButton getStartButton() {
        return startButton;
    }

    public JLabel getInfoLabel() {
        return infoLabel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        topPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        welcomeScrollPane = new javax.swing.JScrollPane();
        welcomeEditorPane = new javax.swing.JEditorPane();
        loadTracksParentPanel = new javax.swing.JPanel();
        summaryTracksPanel = new javax.swing.JPanel();
        summaryTracksSplitPane = new javax.swing.JSplitPane();
        summaryDataParentPanel = new javax.swing.JPanel();
        visualizeTracksParentPanel = new javax.swing.JPanel();
        computationPanel = new javax.swing.JPanel();
        computationSplitPane = new javax.swing.JSplitPane();
        computationDataParentPanel = new javax.swing.JPanel();
        computationGraphParentPanel = new javax.swing.JPanel();
        bottomPanel = new javax.swing.JPanel();
        previousButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        startButton = new javax.swing.JButton();
        infoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cell_Coord");
        setMinimumSize(new java.awt.Dimension(700, 550));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        topPanel.setMinimumSize(new java.awt.Dimension(20, 20));
        topPanel.setPreferredSize(new java.awt.Dimension(20, 20));
        topPanel.setLayout(new java.awt.CardLayout());

        homePanel.setDoubleBuffered(false);
        homePanel.setName("homePanel"); // NOI18N

        welcomeEditorPane.setEditable(false);
        welcomeEditorPane.setContentType("text/html"); // NOI18N
        welcomeEditorPane.setText("<html>   <head> <TITLE></TITLE>   </head>   <body> <a name=\"#top\"/>         <H2>Welcome to Cell_Coord</H2>         <i>A Fiji/ImageJ plugin to study and visualize coordinated cell migration</i>   </body> </html>");
        welcomeScrollPane.setViewportView(welcomeEditorPane);

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
                .addContainerGap())
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                .addContainerGap())
        );

        topPanel.add(homePanel, "homePanel");
        homePanel.getAccessibleContext().setAccessibleName("homePanel");

        loadTracksParentPanel.setName("loadTracksParentPanel"); // NOI18N
        loadTracksParentPanel.setLayout(new java.awt.GridBagLayout());
        topPanel.add(loadTracksParentPanel, "loadTracksParentPanel");
        loadTracksParentPanel.getAccessibleContext().setAccessibleName("loadTracksParentPanel");

        summaryTracksPanel.setMinimumSize(new java.awt.Dimension(20, 20));
        summaryTracksPanel.setName("summaryTracksPanel"); // NOI18N

        summaryTracksSplitPane.setDividerLocation(500);
        summaryTracksSplitPane.setMinimumSize(new java.awt.Dimension(40, 40));

        summaryDataParentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Cell Tracks Summary"));
        summaryDataParentPanel.setLayout(new java.awt.GridBagLayout());
        summaryTracksSplitPane.setLeftComponent(summaryDataParentPanel);

        visualizeTracksParentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Visualize Cell Tracks"));
        visualizeTracksParentPanel.setLayout(new java.awt.GridBagLayout());
        summaryTracksSplitPane.setRightComponent(visualizeTracksParentPanel);

        javax.swing.GroupLayout summaryTracksPanelLayout = new javax.swing.GroupLayout(summaryTracksPanel);
        summaryTracksPanel.setLayout(summaryTracksPanelLayout);
        summaryTracksPanelLayout.setHorizontalGroup(
            summaryTracksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 747, Short.MAX_VALUE)
            .addGroup(summaryTracksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(summaryTracksPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(summaryTracksSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        summaryTracksPanelLayout.setVerticalGroup(
            summaryTracksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
            .addGroup(summaryTracksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(summaryTracksPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(summaryTracksSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        topPanel.add(summaryTracksPanel, "summaryTracksPanel");
        summaryTracksPanel.getAccessibleContext().setAccessibleName("summaryTracksPanel");

        computationPanel.setMinimumSize(new java.awt.Dimension(20, 20));
        computationPanel.setName("computationPanel"); // NOI18N

        computationSplitPane.setDividerLocation(400);
        computationSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        computationSplitPane.setMinimumSize(new java.awt.Dimension(40, 40));
        computationSplitPane.setPreferredSize(new java.awt.Dimension(31, 25));

        computationDataParentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Data"));
        computationDataParentPanel.setPreferredSize(new java.awt.Dimension(25, 25));
        computationDataParentPanel.setLayout(new java.awt.GridBagLayout());
        computationSplitPane.setTopComponent(computationDataParentPanel);

        computationGraphParentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Plot Data"));
        computationGraphParentPanel.setLayout(new java.awt.GridBagLayout());
        computationSplitPane.setBottomComponent(computationGraphParentPanel);

        javax.swing.GroupLayout computationPanelLayout = new javax.swing.GroupLayout(computationPanel);
        computationPanel.setLayout(computationPanelLayout);
        computationPanelLayout.setHorizontalGroup(
            computationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 747, Short.MAX_VALUE)
            .addGroup(computationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(computationPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(computationSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        computationPanelLayout.setVerticalGroup(
            computationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
            .addGroup(computationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(computationPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(computationSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        topPanel.add(computationPanel, "computationPanel");
        computationPanel.getAccessibleContext().setAccessibleName("computationPanel");
        computationPanel.getAccessibleContext().setAccessibleDescription("");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.96;
        getContentPane().add(topPanel, gridBagConstraints);

        bottomPanel.setMinimumSize(new java.awt.Dimension(20, 20));
        bottomPanel.setPreferredSize(new java.awt.Dimension(20, 20));

        previousButton.setText("<< Previous");

        nextButton.setText("Next >>");

        cancelButton.setText("Cancel");

        startButton.setText("Start");

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(previousButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startButton)
                .addContainerGap())
        );

        bottomPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, nextButton, previousButton, startButton});

        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(previousButton)
                    .addComponent(nextButton)
                    .addComponent(cancelButton)
                    .addComponent(startButton))
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.04;
        getContentPane().add(bottomPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CellCoordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CellCoordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CellCoordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CellCoordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel computationDataParentPanel;
    private javax.swing.JPanel computationGraphParentPanel;
    private javax.swing.JPanel computationPanel;
    private javax.swing.JSplitPane computationSplitPane;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JPanel loadTracksParentPanel;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton previousButton;
    private javax.swing.JButton startButton;
    private javax.swing.JPanel summaryDataParentPanel;
    private javax.swing.JPanel summaryTracksPanel;
    private javax.swing.JSplitPane summaryTracksSplitPane;
    private javax.swing.JPanel topPanel;
    private javax.swing.JPanel visualizeTracksParentPanel;
    private javax.swing.JEditorPane welcomeEditorPane;
    private javax.swing.JScrollPane welcomeScrollPane;
    // End of variables declaration//GEN-END:variables
}
